# Generated by Django 5.0.4 on 2024-04-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.CharField(max_length=50)),
                ('enunciado', models.CharField(max_length=250)),
                ('respuesta_correcta', models.CharField(max_length=100)),
                ('respuestas_incorrectas', models.CharField(max_length=250)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
        ),
    ]
